### ISSUE TITLE
Feature request: single line JSON formatted logs

### ISSUE THREAD

**Issue by Crazybus** [elastic/hipio#7]
Right now hipio logs to stdout with multiline logs that look like:

```
2019-12-11 10:41:35 INFO UDP:  {
  "from": "127.0.0.1:34704",
  "answer": "1.2.3.4",
  "server": "hipio-758d95ff75-xw7kb",
  "question": "1.2.3.4.hip.io."
}
```

To make these logs parseable without using multiline and regex filters it would be much nicer to have something that looked more like:

```
{"timestamp": "2019-12-11 10:41:35", "level": "INFO", "transport": "UDP", "from": "127.0.0.1:34704", "answer": "1.2.3.4", "server": "hipio-758d95ff75-xw7kb", "question": "1.2.3.4.ip.es.io."}
```

**Comment by olksdr** [comment]
In order to fix this we need to make changes upstream, which I've PRed at https://github.com/scrive/log/pull/55 

the new format will be a proper jsonline with all the components present inside 
```json
 {"component":"UDP","data":{"from":"127.0.0.1:37392","answer":"1.2.1.1","server":"ec2121e7bdd4","question":"1.2.1.1.example.com."},"insertion_time":" ","message":"","timestamp":"2020-07-18 10:07:27","level":"INFO"}
```

**Comment by olksdr** [comment]
@Crazybus  new hipio release is up if you want to try new jsonlines output : https://github.com/elastic/hipio/releases/tag/v0.5.0
