### ISSUE TITLE
Bug: Stdout log flushing frequency and partial messages

### ISSUE THREAD

**Issue by Crazybus** [elastic/hipio#8]
The current standard out logger isn't flushing after each message. The main issue with this is that when messages are logged only part of the message appears:

Example:

```
2019-12-11 10:58:41 INFO UDP:  {
  "from": "127.0.0.1:36616",
  "answer": "1.2.3.4",
  "server": "hipio-694d565c7-44cgm",
  "question": "1.2.3.4.hip.io."
}
2019-12-11 10:58:42 INFO UDP:  {
  "from": "127.0.0.1:39071",
  "answer": "1.2.3.4",
```

Flushes seem to happen based on the amount of data and doesn't appear to be time based. This may be partially solved by keeping logs single line as proposed in #7.

**Comment by tylerjl** [comment]
Just to verify some assumptions:
- Is this exhibiting on the latest release? (0.4.0)
- Does output flush completely when the program exits?

**Comment by Crazybus** [comment]
> Is this exhibiting on the latest release? (0.4.0)

Yup, 0.4.0 is also the first release to do logging to stdout. 

> Does output flush completely when the program exits?

Nope.

I made a script to help reproduce the problem:

```
#!/bin/bash

cat > Dockerfile << EOL

FROM centos:8

ADD https://github.com/elastic/hipio/releases/download/v0.4.0/hipio /usr/local/bin/hipio
RUN yum install -y bind-utils && \
    chmod +x /usr/local/bin/hipio

ENTRYPOINT [ "/usr/local/bin/hipio" ]
EOL

docker rm -f hipio || true
docker build -t hipio .
docker run --name hipio --rm -d hipio hipio.local --soa-email test.test
docker logs -f hipio
```

After starting it up then running:

```
while true; do docker exec -ti hipio host 1.2.3.4.hipio.local 127.0.0.1; done
```

While this is running you will see batches of results coming through every so often with the latest log line being incomplete. I have been able to reproduce this running with Docker for Mac, Docker directly running on a Linux machine and also when running via a Docker container in Kubernetes. 

One thing that is very odd which I found out while trying to reproduce this is. Is that it does appear to behave correctly when being directly run. If I start a container with `docker run --name hipio --entrypoint=/bin/bash --rm -ti hipio` and then start it directly interactively the logs flush after each entry. So it seems like the behavior might be different if the session is interactive.
